server.port: 8088
logging:
  level:
    root: INFO
  file.name: logs/ctv-vcare.log

jwt:
  secret: venesa
  timetoken:  600000

venesa:
  mail:
    account: anhku0j97@gmail.com
    password: 0915234576

spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/ctv-vcare
#    username: root
#    password: 123456
#    platform: mysql
#    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
      url: jdbc:mysql://10.33.68.24:3306/landingpage
      username: adminlandingpage
      password: ASV20@2020
      platform: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  mail:
    host: smtp.gmail.com
    port: 587
    properties.mail.smtp:
      auth: true
      starttls.enable: true
